### PR TITLE
Show Elo on own user page

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by Skasi** [comment]
Remove '<class="admin">' in line 136, it's a red dashed border used to mark admin-only things.

**Comment by xponen** [comment]
also, might need to add some text saying this is only visible to user.
If not I worry user will worry too much about people judging them thru elo.

**Comment by Anarchid** [comment]
They won't be able to see it on other players' pages, so this should be evident.

**Comment by Licho1** [comment]
Dislike this. Elo is not meant for "ranking" it's only meant to be hidden technical value for team balancing.

**Comment by Skasi** [comment]
> Elo is not meant for "ranking"
http://zero-k.info/Ladders

**Comment by Princereaper** [comment]
Why hav a ladder. I would like to know my elo. What wrong with me knowing my own elo???

**Pull request merged**
