### PR TITLE
Map pool stuff

### PR DESCRIPTION
**Pull request by sprunk**
* 1v1 host only allows maps tagged as 1v1, analogical for teams and FFA
 * Unfeatured and silly maps are only allowed on private hosts

### CODE REVIEW

**Comment by Licho1** [comment]
disagree, its up to people to decide. Its not in default mapcycle, if people do want those maps, they should be allowed to pick them

**Comment by Skasi** [comment]
> Non-supported are not allowed even in private

Definitely against this change. Private games shouldn't have any restrictions.

**Comment by sprunk** [comment]
Removed the "no unsupported maps" (the solution to swastika map spam is not to show private rooms by default in lobby)

**Comment by db81** [comment]
Another solutions is to cycle the map to the next featured when the room becomes empty. That fixes trololo/duck/cow spam as well.

**Comment by sprunk** [comment]
Then you can just keep 1 smurf inside.

**Comment by knorker** [comment]
> Another solutions is to cycle the map to the next featured when the room becomes empty. That fixes trololo/duck/cow spam as well.

No, that is another topic.
The problem is that when you join a room you can never be sure if there will not suddendly be a mapchange to trololo/duck/cow. It is annoying to hope for an RTS match, invest waiting time, then tada! There comes the singing fuckface map.
This PR would be a first step towards at improving https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/921 but sadly some admins block any attempts at fixing the degraded nonsense culture that has developed.

**Comment by CarabusX** [comment]
You are trying to severely limit the ability to test new maps for everyone, including mappers, just because some troll made swastika rooms a few times. This is would mean the troll wins, just like terrorists win IRL when politicians start limiting the freedom of everyone.

**Comment by sprunk** [comment]
>severely limit the ability to test new maps

tagging a map as supported takes literally 10 seconds

**Comment by CarabusX** [comment]
> tagging a map as supported takes literally 10 seconds

But would have to be done to 10000+ maps most of which are valid and playable, just because there are 2 or 3 troll ones. Some others are bugged too, but your point won't apply either, because testing these is definitely not 10 seconds,

**Comment by Skasi** [comment]
> tagging a map as supported takes literally 10 seconds

Nope, it's been a month. http://zero-k.info/Maps/Detail/51571

Relying on inconsistent people to be available and not too lazy to do something is a bad idea.

**Comment by knorker** [comment]
> >tagging a map as supported takes literally 10 seconds
> Nope, it's been a month. http://zero-k.info/Maps/Detail/51571 

No match played on the map, doubtful if someone even tested it offline, no nothing, on what facts should the map be tagged supported? Because you posted:  "Very boxxy." ?

**Comment by knorker** [comment]
also github is as bad trollground as forum now, grats.

**Comment by sprunk** [comment]
>But would have to be done to 10000+ maps most of which are valid and playable

Wouldn't have to. They are so "valid and playable" that 9000 of them have never seen a single game. They are utter shit and nobody actually wants to play them.

Anyway it would be trivial to just mass-support all existing maps which had >0 games on them and pick out the few evil ones. If someone happens to find a valid old map with 0 games it's effectively the same as creating a new one - test it offline first, getting it tagged is the least concern (Skasi just sucks at talking if he couldn't get a map tagged for a month).

**Comment by Skasi** [comment]
> No match played on the map, doubtful if someone even tested it offline

Remember test games that are !exited do not get recorded.

> on what facts should the map be tagged supported?

On facts gathered through proactive science by people responsible for tagging. Or perhaps whatever sprung was thinking.

**Comment by sprunk** [comment]
If there is an existing PvP match on the map, just point to it.

If not, download it and play locally. If it works then contact an admin through PM, report, or forumpost under map (tip: on forum prefer things like "this map works and is playable" instead of "very boxxy").

**Comment by knorker** [comment]
@GoogleFrog

**Comment by Skasi** [comment]
I think before this PR gets accepted someone needs to make sure that things like FFA maps which work fine for team games will be allowed in team rooms. http://zero-k.info/Maps/Detail/7133 comes to mind.

**Comment by CrazyEddieTK** [comment]
Now that the PR has been fixed so that it only applies to public rooms and not private rooms, it should be adopted.

Although isn't it already partially adopted? Isn't it the case that right now non-supported maps can't be chosen in public hosts? If so, then the other part that needs to be adopted is to block special maps from being chosen in public hosts.

**Comment by sprunk** [comment]
No, you can choose any map everywhere currently.

**Comment by Licho1** [comment]
Its now being done by specifying host type when hosting, custom = no restriction, otherwise only proper maps + no modoptions.

**Pull request closed without merging**
