### PR TITLE
Only allow custom modoptions on private hosts

### PR DESCRIPTION
**Pull request by sprunk**
This is done by removing !votesetoptions
Bosses of private rooms can still use !setoptions for a custom game

### CODE REVIEW

**Comment by Licho1** [comment]
I'm not sure about this. What do other people think?>

**Comment by knorker** [comment]
What use is there for modoptions?
The potentially interesting gamemods were never used because lobby made it too difficult to set up and everything was half-broken, until it got removed.

The only modoption I ever see is _metalmult_  which is is used to:
1) to create silly nonsense spam games with +9999 income
2) make tiny maps with few mexes 'more playable' for clusterfuck sized teams.
Both is silly and offputting.

The metalmul modoption is not nessecary to fix bad maps because since years that can be done with lua-metal config file.

**Comment by CrazyEddieTK** [comment]
This should be adopted.

**Comment by Skasi** [comment]
For clarity the Options button in public rooms should be hidden, grayed out or the Options menu - when accessed - should inform players about this once it goes live.

**Comment by Licho1** [comment]
Its being done in new springie-less sytem

**Pull request closed without merging**
