### PR TITLE
Fix ZeroK-RTS/Zero-K#3323

### PR DESCRIPTION
**Pull request by sprunk**
@DeinFreund

### CODE REVIEW

**Comment by DeinFreund** [comment]
See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/0ea610342add7442d490b8afdeac9944481c0d5e

**Comment by sprunk** [comment]
Nice, I thought the ratings were already pre-filled. On the other hand this somewhat ruins my confidence that this will actually fix that other issue.

**Comment by DeinFreund** [comment]
Could you show me a replay with a draw? I wasn't aware that they're actually possible.

**Comment by sprunk** [comment]
Do you want a "real, natural" replay or just a display of game mechanics?

One path to do this is to have all units die at the same time (run two identical starting commanders at each other). I don't think I've personally seen this happen in a real game but querying the DB for a PvP game where everybody died might reveal something.

Another is to have one person drop and have the other resign when presented with the opportunity to perform the inactivity win. The game interprets this as a draw and I believe I've seen this at least once but AFAIK the server misinterprets this as a victory for the dropper (because the dropper technically never died) so it might be hard to query the DB to find this.

**Pull request closed without merging**
