### PR TITLE
remove lua from chobbyla

### PR DESCRIPTION
**Pull request by DeinFreund**

### CODE REVIEW

**Comment by Licho1** [comment]
So what happens when you are offline and not on steam? It wont start then i think..
should be tested in offline mode first.

**Comment by DeinFreund** [comment]
I don't think that was meant to be supported?

**Comment by DeinFreund** [comment]
The engine referenced in modinfo.lua has been the wrong version for months. So using modinfo doesn't really help with offline play.

I originally made a PR that caches the last used engine in a local file, that should be more reliable than modinfo. #2008

**Comment by GoogleFrog** [comment]
Playing offline without steam should work provided you have previously downloaded the right things. Does QueryDefaultEngine() always work?

**Comment by Licho1** [comment]
No thats the thing. Thats why there is the lua fallback. QueryDefaultEngine asks the zero-k.info website.

**Comment by DeinFreund** [comment]
The lua fallback asks chobby modinfo.lua, which currently says `engine          = "104.0.1-287-gf7b0fcc",
`

**Comment by Licho1** [comment]
why did you merge it? Now it wont work offline at all .. if our server goes down ..

**Comment by Licho1** [comment]
i dont think it should be merged, its also in use for testing scenarios when you dont want to run local site with ZK to respond to query engine

**Comment by DeinFreund** [comment]
It runs offline with steam, it doesn't run offline without steam. For testing you can adjust the default engine in GlobalConst. The engine given by Chobby lua crashes the game.

**Comment by Licho1** [comment]
ok, accepted by me then

**Comment by GoogleFrog** [comment]
It should run offline without steam. Are you saying that it will simply crash now without steam?

**Comment by DeinFreund** [comment]
No, that was never a supported configuration.

**Comment by Licho1** [comment]
I am pretty sure it was at a point

**Comment by Anarchid** [comment]
Just FYI, the issue that indirectly precipitated this PR (my inability to mkbundle the old minimal build of chobbyla with modern mono/mkbundle) was resolved to an mkbundle issue and workarounded as such.

**Pull request merged**
