### PR TITLE
Added checkbox so users can tag uploaded maps as special.

### PR DESCRIPTION
**Pull request by Aquanim**
I can't easily test this locally so somebody who actually understands infra should check this before pulling.

### CODE REVIEW

**Comment by DeinFreund** [comment]
This will likely conflict with @maackey's changes.

**Comment by Aquanim** [comment]
For reference the reason for this PR is that retrospectively tagging a bunch of ZeroWars replays as noelo is a pain in the neck.

**Comment by DeinFreund** [comment]
Yes I totally understand. That's exactly the use case I'd expect it to be used for. Just asking maackey to check whether he wants to merge his changes soon, and in this case would rather just include this in his UI overhaul.

**Comment by maackey** [comment]
This is only a few lines it looks like it will be pretty easy to merge

**Pull request merged**
