### PR TITLE
Springie comsharing

### PR DESCRIPTION
**Pull request by sprunk**
If comsharing modoption is enabled, Springie will make the teams comshared.

### CODE REVIEW

**Comment by Licho1** [comment]
this wont really work because ZKL forces unique teamid...

**Comment by sprunk** [comment]
This is for the autobalance that happens just before start, ZKL wont have time to change before start (and ZKL can be changed to allow comshare too)

**Comment by Licho1** [comment]
imo its a bad place to do it, we are moving away from lobby defined teams etc, there is also server balance which transmits ful llist of ally/ids it can be done there at will...

**Comment by Licho1** [comment]
I would rather merge a complete solution rather than half of support for non zkl lobbies...

**Comment by sprunk** [comment]
It happens in Springie's balance so it doesn't matter what lobby the players use.
It also uses the server list of ally/IDs (it reads from it and uses allyID for teamID).

**Comment by Licho1** [comment]
This is not the place though... there is another one in spring.cs

**Comment by Licho1** [comment]
Also should it really be per entire alliance? Perhaps it can be clan based or something like that.. dunno..

**Comment by sprunk** [comment]
This is mostly for tourneys and super-competitive settings so it can be per entire alliance for now and if it is wanted it can later be extended to multiple levels using the modoption (eg. none/clans/everyone).

**Comment by Licho1** [comment]
ok

**Pull request merged**
