### PR TITLE
Use module pictures from Github, not Google Code

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by Licho1** [comment]
Copy those to local server on deployment instead

**Comment by xponen** [comment]
okay, Anarchid said same thing, but I didn't understand how it work. I don't know what Anarchid would do.

**Comment by Anarchid** [comment]
I suspect xponen might lack admin privs on teamcity to do it.

**Comment by sprunk** [comment]
module pictures are already on the local server
they are deployed using the avatar deployment, not game deployment though

**Comment by Anarchid** [comment]
Excellent!

**Pull request merged**
