### PR TITLE
1v1 weight done the other way

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by Licho1** [comment]
You cannot use effective elo it would lead to non-zero sum because of malus...

**Comment by sprunk** [comment]
That would be only for the win chance calculation (like it already is for teams, see https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZkData/Ef/SpringBattle.cs#L128 ).

**Comment by Licho1** [comment]
ok

**Comment by Licho1** [comment]
I mean we can keep it this way i suppose.

**Comment by sprunk** [comment]
"This way"? This here is a PR not a commit.

**Pull request closed without merging**
