### PR TITLE
Don't count AFK players for votes

### PR DESCRIPTION
**Pull request by DeinFreund**
see #1736 

This might have some unintended side effects.

### CODE REVIEW

**Comment by sprunk** [comment]
What kind of side effects?

**Comment by DeinFreund** [comment]
This affects all polls, not just spectating, so maybe I didn't think of something.

**Comment by sprunk** [comment]
Why can't the boss handle afkers?

**Comment by DeinFreund** [comment]
This is about votes, those should work independently of the boss. Also in practice the boss is often afk/offline while people are still playing in his room.

**Comment by DeinFreund** [comment]
This is bad in practice. If somebody afks in a room, the joiner can instantly !poll start.

**Comment by sprunk** [comment]
Use the MM if you want to get a notification before a battle.
Host your own room where you are the boss if you don't want to leave yourself to other people's vote.
Don't afk in a public vote room.

**Pull request merged**
