### PR TITLE
forum: donator star link to contib page

### PR DESCRIPTION
**Pull request by mojjj**
as per request from 
http://zero-k.info/Forum/Thread/11435

link goes to
http://zero-k.info/Forum/Thread/867

### CODE REVIEW

**Comment by Anarchid** [comment]
should go to zero-k.info/Contributions, which is a page rather than a forum topic

**Comment by mojjj** [comment]
i agree. BUT. compare the pages and look which one has better infos to donate, which is why i used this.

**Comment by mojjj** [comment]
meaning contrib pages is so 2013 and incomplete

**Comment by Anarchid** [comment]
The prudent solution is then to upgrade the page.

**Comment by mojjj** [comment]
#397

**Comment by KingRaptor** [comment]
Contrib pages may be 2013 but forum thread is 2012.

Anyway, pulling.

**Pull request merged**
