### PR TITLE
"Blind" attempt at fixing NW report droppage

### PR DESCRIPTION
**Pull request by sprunk**
Sometimes messages can get through which suggests a race condition, nobody else has any better idea so won't hurt to try.

### CODE REVIEW

**Comment by Licho1** [comment]
There was probably no await on purpose, to make it async from the point of user

**Comment by sprunk** [comment]
8d4a86937e53ac89454016de2aa37ee34c03a0c9 my vision is augmented

**Comment by Licho1** [comment]
The referenced commits I am not sure since it will require async controller too..

**Comment by sprunk** [comment]
@DeinFreund ^

**Pull request closed without merging**
