### PR TITLE
welcome_screen, ZKL: add simple local replay form

### PR DESCRIPTION
**Pull request by xponen**
this form is currently not attached to MainWindow

is useful & address issue https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/524

Note, there was tiny line-end diff on ZeroKLobby.csproj, can safely ignore

### CODE REVIEW

**Comment by xponen** [comment]
want to PR to master

**Comment by Licho1** [comment]
whatever breaks merging of wlecome screen will be reverted

**Comment by xponen** [comment]
I can help you merge and resolve conflict. Its easy now, I've practice

**Comment by xponen** [comment]
I can push from my side, to you, I can edit from my PC

**Comment by Licho1** [comment]
Well new ZKL is 100x more important than this and you know it, if there is a merge problem it should not block new ZKL but instead this feature.

**Comment by Licho1** [comment]
Wait a moment i misunderstood. You want to merge this to master, ok... you can also wait until welcome screen merge, it can be soon just needs two more screens finished. Mp and downloads and its ok for initial release

**Comment by xponen** [comment]
I'm practicing resolving conflict:
Is practicing:
xponenLocalReplayFormForMasters ---->> master        (zkl &zklNet4) 
                                                                    |
                              welcome_screen  <<---- /              (new_zkl)
                                      |
                                     V
                              Conflict:
                                    - remove Extra tab
                                    +"include" lines in ZeroKLobby.csproj
                              Ignore:
                                    +several Net4.0 files

**Pull request closed without merging**
