### PR TITLE
GlobalConst: make 98.0.1-398-g80e6cfa default to try to workaround #529

### PR DESCRIPTION
**Pull request by Anarchid**

### CODE REVIEW

**Comment by Licho1** [comment]
This has massive consequences. Make 100% sure it works even for new users - that for example ZKL starts mission on 98 properly

**Comment by Licho1** [comment]
(With nothing preinstalled)

**Comment by Anarchid** [comment]
Hm. Will test more, revert if breaks.

**Comment by Anarchid** [comment]
Missions seemed to work on a machine completely purged out of anything ZK.

I think the installer is not automatically updated, because it tried to dowload 91.0 initially and also immediately demanded an update.

**Comment by Licho1** [comment]
Installer contains no mod or mod download.

**Comment by Anarchid** [comment]
Hmm, right, it did download zero-k.exe before installing it. Does that mean that there's another obscure global somewhere telling it to dl 91?

**Comment by Licho1** [comment]
It might be in the mission or mission script i dont know..

2015-03-06 11:03 GMT+01:00 Анархид <notifications@github.com>:

**Pull request merged**
