### PR TITLE
Planet wars: remove E → M conversion

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by GoogleFrog** [comment]
You changed a non-zero value to zero. How will this not break?

**Comment by sprunk** [comment]
Because it's used as `metal = energy * ratio`.

**Comment by sprunk** [comment]
Caveat from https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1705#issuecomment-293519942

>Dropships were pretty high-powered, though (...) Reducing OD efficiency will increase dropship power.

**Comment by Licho1** [comment]
Why do you want to do this? It is to give more options when building your empire - you can focus on metal farming by just building energy and not energy sinks.

**Comment by sprunk** [comment]
@Licho1, see @GoogleFrog's comment: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1838#issuecomment-339336844

> Remove automatic energy to metal conversion. This is to make early energy overproduction not a trivial decision.

**Comment by GoogleFrog** [comment]
I claim that E -> M conversion does not really give you more options and leads to unstable economic harassment gameplay. Note that E -> M conversion makes the economy effectively work as follows, with a few caveats:
- Power structures generate metal.
- Most other structures drain metal as upkeep.

Every faction wants to increase its metal income in order to make better infrastructure, especially in a FFA. Therefore they are going to build as much power as they can while building as few other structures as possible. The investment in power structures supports their later infrastructure because they need the extra metal income (energy in the actual game) to pay the upkeep of their infrastructure. If infrastructure had no metal upkeep cost then power structures would be more of a choice.

Factions may also build a little bit of infrastructure to perform quick strikes against the enemy economy or pre-emptive strikes to defend their own, but only if this is efficient (remember it's FFA). Quick, efficient, strikes run counter to the goals of planetwars (to involve all players in a lengthy war) because they are likely to be done by the top players against the weaker players of the other faction. This leads to blaming and excessive timezone optimization instead of teamwork. Ideally there will be relatively important/unimportant battles but they should not outweigh the actions of the rest of the faction. This is also why I dislike superweapons, something really important happened but few people brought it about.

Quick strikes (with warp cores) are effective because they can deal damage to an exponential economy. The exponential economy comes from power generators and everyone has exposed planets covered in power generators. The planets are exposed because there are a lot of planets and the defense structures drain metal upkeep. These dynamics make pre-emptive warp core rushes highly effective. First you can kill their core/dropship production and then you can make economic gains against them. The only thing keeping this in check is FFA dynamics.

Reliance on FFA dynamics to prevent early quick strike rushes is terrible because it will cause a highly unstable game in which one faction may win early. We want the FFA dynamics to regulate the expansion and victory point control of the currently winning faction in the mid to late game. Ideally planetwars would eventually be won by a faction reaching the victory point total. It should be very difficult to entirely halt the gaining of victory points throughout the galaxy, to ensure that the game doesn't stagnate (this can all be balanced through the database).

Anyway, that is why I want to remove E -> M conversion. I want power structures to be relegated to the role of population cap for infrastructure. This population cap only has two purposes in the game mechanics:
- It makes the initial construction of a piece of infrastructure more expensive than rebuilding that infrastructure.
- It lets factions reconfigure their infrastructure without re-paying the cost of the power structure.

Also, as with all structures, power structures are cool to see on planets and protect/destroy. A non-exponential economy will dampen down the effect of the early game and so will not encourage early quick strikes. After thinking about these exponential economies I am now in favour of adding a metal upkeep for ship factories (see https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1852). I am also considering a dedicated metal production structure because that would be more of a choice. However, while it is worth adding support in the database, I don't think we need to add it to the next round of planetwars.

**Comment by Licho1** [comment]
Ok, lets try this.

**Comment by Licho1** [comment]
Btw don't forget there is still this: PlanetMetalPerTurn = 1;

**Comment by GoogleFrog** [comment]
Planet metal per turn is fine. An income of 1 is relatively small compared to the amounts that power plants were generating and the number of planets is limited. I think it is unusual for a faction to own more than 30 planets and this income would only be half the expected 66 metal income gained from battles per turn. In most cases the faction with the most planets won't have more than 15 more planets than the faction with the least planets so in practise the effect will be quite small.

**Pull request merged**
