### PR TITLE
remove accept requests from mm

### PR DESCRIPTION
**Pull request by DeinFreund**
Just start whatever battle is possible. AFK players need to be removed from queue by lobby.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
I'm highly against this. Removing accept is terrible because you'll end up loading battles which don't occur.

**Comment by DeinFreund** [comment]
The idea is to move the accept part to joining the queue. Assuming queue wait times are 2 minutes at most, this should be fairly equal to accepting the game itself.

The hard part is making sure people are still active when queue wait times exceed those 2 minutes. For this, the lobby could ask players if they want to remain in the queue if it detects afk.

**Comment by sprunk** [comment]
>the lobby could ask players if they want to remain in the queue if it detects afk

This is what accept does, except doesn't boot out people prematurely.

>Assuming queue wait times are 2 minutes at most

Pretty bold assumption.

**Comment by sprunk** [comment]
Superseded by #2258 (by setting interval = 9001)

**Pull request closed without merging**
