### PR TITLE
Max players in room: 32 -> 200

### PR DESCRIPTION
**Pull request by DeinFreund**
probably not, but alcur would love it.

### CODE REVIEW

**Comment by sprunk** [comment]
regardless of the value I think it should be a GlobalConst

**Comment by DeinFreund** [comment]
If it works we can make it a globalconst. I'd rather not add a globalconst that doesn't actually work and confuses people.

**Comment by Licho1** [comment]
it does work but why do you want to increase it?

**Comment by DeinFreund** [comment]
Alcur said it would improve games.

**Comment by Licho1** [comment]
well first get 200 people then this :-)

**Pull request closed without merging**
