### PR TITLE
quickfix for dead springies

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by Licho1** [comment]
WTF are you doing. Startbox control from springie is needed for planetwars

**Comment by Licho1** [comment]
And server knowledge of boxes is needed for skirmish and other features.

**Comment by sprunk** [comment]
its not real startboxes, its a modoption

**Comment by Licho1** [comment]
line 316 is real startboxes

2015-05-20 9:26 GMT+02:00 sprunk <notifications@github.com>:

**Comment by sprunk** [comment]
lol ok

**Comment by Orfelius** [comment]
*waves hand
Umh hello Springiees are non functional right now can the latest change to it just get reverted now?

**Pull request merged**
