### PR TITLE
google ranks

### LINKED ISSUE #1205: Make rank progression nicer
Rank progression should have players gain a new rank image at levels 5, 10, 20, 35, 50, 75 and 100.

### PR DESCRIPTION
**Pull request by DeinFreund**
fix #1205 

brackman will enjoy

### CODE REVIEW

**Comment by db81** [comment]
dein_formula

**Comment by Licho1** [comment]
Zomg

**Comment by DeinFreund** [comment]
Diplomacy: Brackman wants ln(x) based formula, GoogleFrog wants arbitrary mapping -> this.

**Comment by Licho1** [comment]
What program you used to fit the curve??

**Pull request merged**
