### PR TITLE
Merge Master into Stable again

### PR DESCRIPTION
**Pull request by xponen**
Zero-K NET4.0 can't build, it make auto-build stuck, maybe after changing name to Zero-K_NET4.0 it might work?

### CODE REVIEW

**Comment by Licho1** [comment]
Please dont store ZKL 4 in master anymore, since we decided its not a maintainable but one time "compile" only change no need to do that..
You would have to port entire new ZKL which is massive change with 1200 changed files..

**Comment by xponen** [comment]
maybe when new ZKL release I can slowly put all the stuff into ZKLNET4?

**Comment by Licho1** [comment]
Whats the point, you can make ZKL 4 at any time by doing 3 simple steps..
change projects to .net 4.0 (does not matter that many wont compile), add async BCL, done

**Comment by xponen** [comment]
is that easy??
wont we have to change the event handler in TasClient, and change Task to TaskEx, and edit reference to async BCL too?

**Comment by Licho1** [comment]
Ok and cahnge Task to TaskEx but I believe it can be done in 5 mins or so when it's trained a bit. So I think it will be less wor than maintaining entire folder like this.

**Comment by xponen** [comment]
idk... at moment is still okay for me IMO,

My step is:
I copy paste original folder
  ZeroKLobby, PlasmaShared, LobbyClient, MonoTorrent, and PlasmaDownloader 
into ZeroKLobby_NET4.0, then overwrite all files, then using what I remember for NET4.0 conversion steps, to check file diff 1-by-1 using Tortoise Commit window to avoid changing the NET4.0 stuff.

Then if ZKL changes, I would replace ZeroKLobby_NET4.0.csproj with original ZeroKLobby.csproj and carefully check file diff using Tortoise again.

Maybe at moment is okay, if it get too hard, then I surrender...

**Comment by Licho1** [comment]
Yeah but try merging this into welcome_screen :-)
Thats what i have to do now

**Comment by xponen** [comment]
ooo noo...

**Comment by xponen** [comment]
let me help, I will spend time resolve conflict 1 by 1, and readd NET4.0 so I won't need to copy paste again later ...
pls

**Comment by xponen** [comment]
maybe I include new ZKL into NET4.0 at same time!

**Pull request merged**
