### PR TITLE
Master -> Stable

### PR DESCRIPTION
**Pull request by Anarchid**

### CODE REVIEW

**Comment by Anarchid** [comment]
I'm getting more annoyed by replay failures, so maybe it's about time to put the 20s debug thing into deployment soon.

**Comment by Licho1** [comment]
Merge at will, best when population is low and you hang arouind to fix issues or revert merge

**Comment by Anarchid** [comment]
I'll fire it up this morning.

**Comment by Jamanno** [comment]
next time wait until game end. Thank you.

**Pull request merged**
