### PR TITLE
splitting queues and making things more readable

### PR DESCRIPTION
**Pull request by Rekojeht**
split queues as suggested here https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2234

and made BannedSeconds more readable

ref: Issue #2234

### CODE REVIEW

**Comment by DeinFreund** [comment]
Code looks good, but I'm unsure whether we want to add so many queues and use the same map pool for 2v2 and 5v5.

**Comment by sprunk** [comment]
Yeah if you're adding 5v5 then the map pool should be reconsidered because it's starting to get large. IMO just split into 2 3 4 for now.

**Comment by MikeHolder** [comment]
Okay, I removed 5v5. I think Licho mentioned it so that's why I had it there. :)

**Comment by GoogleFrog** [comment]
Splitting queues has the dangerous side-effect of making it harder to find games if people sit in individual queues. The UI needs to push people towards joining multiple queues at once. Also I forget whether the space scales automatically or needs a lobby update.

Anyway, looks like a decent change.

**Pull request merged**
