### PR TITLE
adjust icons

### PR DESCRIPTION
**Pull request by Anarchid**
replaces ugly multiplayer icon
add alternative web icon (not applied; discuss)

### CODE REVIEW

**Comment by KingRaptor** [comment]
I like the web icon.

The new MP icon is good but I find myself oddly attached to the conjoined twins >__<

**Comment by db81** [comment]
The twins read more like "play with friends" than MP, so if you're attached we could perhaps use them somewhere in that vein.

**Comment by Licho1** [comment]
Yeah i would like to use MP for overlay, and keep current for button, need to cherry pick this later.

**Comment by Licho1** [comment]
ZKL now uses these icons (merged manually to avoid overwrite of MP)

**Pull request closed without merging**
