### PR TITLE
Add "supported" tag for maps

### PR DESCRIPTION
**Pull request by KingRaptor**
Now using its own DB column

### CODE REVIEW

**Comment by Licho1** [comment]
Oops i forgot to merge it, it has to be changed for C# code first now, i can help to guide - ideal mini tutorial

**Comment by Licho1** [comment]
To reimplement this DB change do this:

1) open package manager window in VS http://i.imgur.com/MYiQTcg.png 
2) in the window set "default project" to "ZkData"
3) "update-database" into the package manager window, this will create your local db structure to match the servers (this is only needed first time)
4) modify the resource class - simply add the MapIsSupported c# property 
5) "add-migration SomeName" into the package manager window will create new migration class - review that and if happy commit

**Comment by KingRaptor** [comment]
It turns out all the needed DB changes were already done during the migration, reopening and pulling.

**Comment by knorker** [comment]
In past it was often discussed that just a boolean supported-tag would not be enough.
If multiple mods are supposed to be playable (which I understood was still a goal) then a way to indicate *which mod* the map supports is nessecary. 
Some of those threads are linked in this issue, too. 

Either that the lobby's map-selection reads the mod's https://springrts.com/wiki/Validmaps.lua or by having a supported-tag that can be set seperately for different games.

This also does not solve the problem of "silly" maps:
For zero-K a map might be "silly" but for another game it might be normal.

**Comment by KingRaptor** [comment]
> If multiple mods are supposed to be playable (which I understood was still a goal)

I can only speak for myself, but with the way server split went this is probably no longer the case. At least there is unlikely to be any particular effort to guarantee support.

**Pull request merged**
